---
- hosts: 12.12.12.12
  gather_facts: yes
  become: true
  vars:
    ansible_ssh_private_key_file: /home/ansible/awskey/ansible.pem
    ansible_user: ubuntu
  tasks:
    - name: Display gathered facts
      debug:
        var: ansible_facts
  tasks:
    - name: Install Apache for Ubuntu
      become: true
      package:
        name: apache2
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'ubuntu'

    - name: Install dotnet-sdk-6.0
      become: true
      shell: >
        wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft->
        sudo dpkg -i packages-microsoft-prod.deb &&
        sudo apt-get update &&
        sudo apt-get install -y dotnet-sdk-6.0

    - name: Create directories
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /etc/systemd/system/test.service
        - /etc/httpd/conf
        - /var/www/html/testproject
